export const shapes = [
  [{
    name: 'rectangle',
    style: [{
      'backgroundColor':'{color}',
      'width': '{width}',
      'height': '{height}',
    }],
    active:true,
    saveKey:'r',
  }],
  [{
    name: 'circle',
    style: [{
      'borderRadius':'50%',
      'backgroundColor':'{color}',
      'width': '{width}',
      'height': '{height}',
    }],
    active:false,
    saveKey:'c',
  }],
  [{
    name: 'halfcircle',
    style: [{
      'borderRadius':'50% / 100% 100% 0 0',
      'backgroundColor':'{color}',
      'width': '{width}',
      'height': '{height}',
    }],
    active:false,
    saveKey:'h',
  },
  {
    name: 'halfcircleangle',
    ratio: '1:1',
    style: [
      {
        'borderRight': '{width/2} solid transparent',
        'borderTop': '{width/2} solid transparent',
        'borderRadius':'{width/2}',
        'borderLeft': '{width/2} solid {color}',
        'borderBottom': '{width/2} solid {color}',
        'width': '{width}',
        'height': '{height}',
      },
      {
        'borderTop': '{width/2} solid transparent',
        'borderLeft': '{width/2} solid transparent',
        'borderRadius':'{width/2}',
        'borderRight': '{width/2} solid {color}',
        'borderBottom': '{width/2} solid {color}',
        'width': '{width}',
        'height': '{height}',
      },
      {
        'borderRight': '{width/2} solid transparent',
        'borderBottom': '{width/2} solid transparent',
        'borderRadius':'{width/2}',
        'borderLeft': '{width/2} solid {color}',
        'borderTop': '{width/2} solid {color}',
        'width': '{width}',
        'height': '{height}',
      },
      {
        'borderLeft': '{width/2} solid transparent',
        'borderBottom': '{width/2} solid transparent',
        'borderRadius':'{width/2}',
        'borderRight': '{width/2} solid {color}',
        'borderTop': '{width/2} solid {color}',
        'width': '{width}',
        'height': '{height}',
      },
    ],
    active:false,
    saveKey:'a',
  }],
  [{
    name: 'quartercircle',
    style: [
      {
        'borderRadius':'0 0 100% 0',
        'backgroundColor':'{color}',
        'width': '{width}',
        'height': '{height}',
      },
                  {
                  'borderRadius':'0 0 0 100%',
                  'backgroundColor':'{color}',
                  'width': '{width}',
                  'height': '{height}',
                  },
      {
      'borderRadius':'0 100% 0 0',
      'backgroundColor':'{color}',
      'width': '{width}',
      'height': '{height}',
      },
      {
      'borderRadius':'100% 0 0 0',
      'backgroundColor':'{color}',
      'width': '{width}',
      'height': '{height}',
      },
    ],
    active:false,
    saveKey:'q',
  },
  {
    name: 'cone',
    style: [{
      borderRadius: '50%',
      'width': '{width}',
      'height': '{height}',
      'borderLeft': '{width} solid transparent',
      'borderRight': '{width} solid transparent',
      'borderTop': '{height} solid {color}',
    }],
    active:false,
    saveKey:'w',
  }],
  [{
    name: 'triangle',
    style: [{
      'width': '{width}',
      'height': '{height}',
      'borderLeft': '{width/2} solid transparent',
      'borderRight': '{width/2} solid transparent',
      'borderBottom': '{height} solid {color}',
    }],
    active:false,
    saveKey:'t',
  }],
];